name: Create Release and Zip Deploy Folder 1

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Deploy Folder
      run: |
        TIMESTAMP=$(date +"%m%d%Y%H%M")
        ZIP_NAME="deploy-${TIMESTAMP}.zip"  # Correctly capture the dynamic zip name
        cd 64a5ba565d5c575e83b6e23e
        zip -r ../$ZIP_NAME ./*
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        cd ..
    - name: Upload Zip as Artifact  # Use the dynamic zip name for the artifact path
      uses: actions/upload-artifact@v2
      with:
        name: deploy-package  # Keep the artifact name consistent
        path: ${{ env.ZIP_NAME }}  # Use the dynamic ZIP_NAME environment variable

  release:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: deploy-package  # Ensure this matches the name used in the upload step
    - name: Create Release
      run: |
        RESPONSE=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{\"tag_name\": \"${{ github.ref_name }}\", \"name\": \"Release ${{ github.ref_name }}\", \"body\": \"Release description here\", \"draft\": false, \"prerelease\": false}")
        echo "$RESPONSE"
        UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url | sed 's/{?name,label}//')
        echo "UPLOAD_URL=$UPLOAD_URL"
        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
    - name: Upload Release Asset
      run: |
        echo "Using UPLOAD_URL: $UPLOAD_URL"
        ZIP_PATH="${{ github.workspace }}/${{ env.ZIP_NAME }}"
        echo "Uploading file at $ZIP_PATH"
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/zip" \
          --data-binary "@${ZIP_PATH}" \
          "${UPLOAD_URL}?name=$(basename $ZIP_PATH)"
      env:
        UPLOAD_URL: ${{ env.UPLOAD_URL }}

