name: Create Release and Zip Deploy Folder

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Deploy Folder
      run: |
        zip -r deploy.zip ./64a5ba565d5c575e83b6e23e
    - name: Upload Zip as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: deploy.zip

  release:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: deploy
    - name: Create Release
      run: |
        RESPONSE=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{\"tag_name\": \"${{ github.ref_name }}\", \"name\": \"Release ${{ github.ref_name }}\", \"body\": \"Release description here\", \"draft\": false, \"prerelease\": false}")
         echo "$RESPONSE"
        UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url | sed 's/{?name,label}//')
        echo "UPLOAD_URL=$UPLOAD_URL"
        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
    - name: Upload Release Asset
      run: |
        echo "Using UPLOAD_URL: $UPLOAD_URL"
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/zip" \
          --data-binary @deploy.zip \
          "$UPLOAD_URL?name=$(basename ./deploy.zip)"
      env:
        UPLOAD_URL: ${{ env.UPLOAD_URL }}
